runtime: python39

entrypoint: gunicorn -b :$PORT app:app

instance_class: F2  # Choose an instance type, e.g., F2, F4, etc.

env_variables:
  STREAMLIT_SERVER_HEADLESS: "true"
  STREAMLIT_SERVER_PORT: "$PORT"

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 2
